# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import biometry_pb2 as biometry__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in biometry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatekeeperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/biometry.Gatekeeper/RegisterUser',
                request_serializer=biometry__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=biometry__pb2.IdResponse.FromString,
                _registered_method=True)
        self.AddBiometry = channel.unary_unary(
                '/biometry.Gatekeeper/AddBiometry',
                request_serializer=biometry__pb2.AddBiometryRequest.SerializeToString,
                response_deserializer=biometry__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveUser = channel.unary_unary(
                '/biometry.Gatekeeper/RemoveUser',
                request_serializer=biometry__pb2.IdRequest.SerializeToString,
                response_deserializer=biometry__pb2.Empty.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/biometry.Gatekeeper/ListUsers',
                request_serializer=biometry__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=biometry__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.AddZone = channel.unary_unary(
                '/biometry.Gatekeeper/AddZone',
                request_serializer=biometry__pb2.AddZoneRequest.SerializeToString,
                response_deserializer=biometry__pb2.IdResponse.FromString,
                _registered_method=True)
        self.ListZones = channel.unary_unary(
                '/biometry.Gatekeeper/ListZones',
                request_serializer=biometry__pb2.ListZonesRequest.SerializeToString,
                response_deserializer=biometry__pb2.ListZonesResponse.FromString,
                _registered_method=True)
        self.AddRoom = channel.unary_unary(
                '/biometry.Gatekeeper/AddRoom',
                request_serializer=biometry__pb2.AddRoomRequest.SerializeToString,
                response_deserializer=biometry__pb2.IdResponse.FromString,
                _registered_method=True)
        self.ListRooms = channel.unary_unary(
                '/biometry.Gatekeeper/ListRooms',
                request_serializer=biometry__pb2.ListRoomsRequest.SerializeToString,
                response_deserializer=biometry__pb2.ListRoomsResponse.FromString,
                _registered_method=True)
        self.AddDevice = channel.unary_unary(
                '/biometry.Gatekeeper/AddDevice',
                request_serializer=biometry__pb2.AddDeviceRequest.SerializeToString,
                response_deserializer=biometry__pb2.IdResponse.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/biometry.Gatekeeper/ListDevices',
                request_serializer=biometry__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=biometry__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.RemoveDevice = channel.unary_unary(
                '/biometry.Gatekeeper/RemoveDevice',
                request_serializer=biometry__pb2.IdRequest.SerializeToString,
                response_deserializer=biometry__pb2.Empty.FromString,
                _registered_method=True)
        self.GrantAccess = channel.unary_unary(
                '/biometry.Gatekeeper/GrantAccess',
                request_serializer=biometry__pb2.GrantAccessRequest.SerializeToString,
                response_deserializer=biometry__pb2.Empty.FromString,
                _registered_method=True)
        self.SetAccessRules = channel.unary_unary(
                '/biometry.Gatekeeper/SetAccessRules',
                request_serializer=biometry__pb2.SetAccessRulesRequest.SerializeToString,
                response_deserializer=biometry__pb2.Empty.FromString,
                _registered_method=True)
        self.GetUserAccess = channel.unary_unary(
                '/biometry.Gatekeeper/GetUserAccess',
                request_serializer=biometry__pb2.IdRequest.SerializeToString,
                response_deserializer=biometry__pb2.GetUserAccessResponse.FromString,
                _registered_method=True)
        self.CheckAccess = channel.unary_unary(
                '/biometry.Gatekeeper/CheckAccess',
                request_serializer=biometry__pb2.CheckAccessRequest.SerializeToString,
                response_deserializer=biometry__pb2.AccessCheckResponse.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/biometry.Gatekeeper/GetSystemStatus',
                request_serializer=biometry__pb2.Empty.SerializeToString,
                response_deserializer=biometry__pb2.SystemStatusResponse.FromString,
                _registered_method=True)
        self.ControlService = channel.unary_unary(
                '/biometry.Gatekeeper/ControlService',
                request_serializer=biometry__pb2.ControlServiceRequest.SerializeToString,
                response_deserializer=biometry__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ControlDoor = channel.unary_unary(
                '/biometry.Gatekeeper/ControlDoor',
                request_serializer=biometry__pb2.ControlDoorRequest.SerializeToString,
                response_deserializer=biometry__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ScanHardware = channel.unary_unary(
                '/biometry.Gatekeeper/ScanHardware',
                request_serializer=biometry__pb2.Empty.SerializeToString,
                response_deserializer=biometry__pb2.ScanHardwareResponse.FromString,
                _registered_method=True)
        self.GetLogs = channel.unary_unary(
                '/biometry.Gatekeeper/GetLogs',
                request_serializer=biometry__pb2.GetLogsRequest.SerializeToString,
                response_deserializer=biometry__pb2.GetLogsResponse.FromString,
                _registered_method=True)


class GatekeeperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterUser(self, request, context):
        """--- Пользователи ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBiometry(self, request, context):
        """NEW
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddZone(self, request, context):
        """--- Инфраструктура ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListZones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantAccess(self, request, context):
        """--- Контроль Доступа ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAccessRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """--- Управление системой и Оборудованием ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlDoor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanHardware(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLogs(self, request, context):
        """--- Журнал ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatekeeperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=biometry__pb2.RegisterUserRequest.FromString,
                    response_serializer=biometry__pb2.IdResponse.SerializeToString,
            ),
            'AddBiometry': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBiometry,
                    request_deserializer=biometry__pb2.AddBiometryRequest.FromString,
                    response_serializer=biometry__pb2.Empty.SerializeToString,
            ),
            'RemoveUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUser,
                    request_deserializer=biometry__pb2.IdRequest.FromString,
                    response_serializer=biometry__pb2.Empty.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=biometry__pb2.ListUsersRequest.FromString,
                    response_serializer=biometry__pb2.ListUsersResponse.SerializeToString,
            ),
            'AddZone': grpc.unary_unary_rpc_method_handler(
                    servicer.AddZone,
                    request_deserializer=biometry__pb2.AddZoneRequest.FromString,
                    response_serializer=biometry__pb2.IdResponse.SerializeToString,
            ),
            'ListZones': grpc.unary_unary_rpc_method_handler(
                    servicer.ListZones,
                    request_deserializer=biometry__pb2.ListZonesRequest.FromString,
                    response_serializer=biometry__pb2.ListZonesResponse.SerializeToString,
            ),
            'AddRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRoom,
                    request_deserializer=biometry__pb2.AddRoomRequest.FromString,
                    response_serializer=biometry__pb2.IdResponse.SerializeToString,
            ),
            'ListRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRooms,
                    request_deserializer=biometry__pb2.ListRoomsRequest.FromString,
                    response_serializer=biometry__pb2.ListRoomsResponse.SerializeToString,
            ),
            'AddDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDevice,
                    request_deserializer=biometry__pb2.AddDeviceRequest.FromString,
                    response_serializer=biometry__pb2.IdResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=biometry__pb2.ListDevicesRequest.FromString,
                    response_serializer=biometry__pb2.ListDevicesResponse.SerializeToString,
            ),
            'RemoveDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDevice,
                    request_deserializer=biometry__pb2.IdRequest.FromString,
                    response_serializer=biometry__pb2.Empty.SerializeToString,
            ),
            'GrantAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantAccess,
                    request_deserializer=biometry__pb2.GrantAccessRequest.FromString,
                    response_serializer=biometry__pb2.Empty.SerializeToString,
            ),
            'SetAccessRules': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccessRules,
                    request_deserializer=biometry__pb2.SetAccessRulesRequest.FromString,
                    response_serializer=biometry__pb2.Empty.SerializeToString,
            ),
            'GetUserAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAccess,
                    request_deserializer=biometry__pb2.IdRequest.FromString,
                    response_serializer=biometry__pb2.GetUserAccessResponse.SerializeToString,
            ),
            'CheckAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAccess,
                    request_deserializer=biometry__pb2.CheckAccessRequest.FromString,
                    response_serializer=biometry__pb2.AccessCheckResponse.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=biometry__pb2.Empty.FromString,
                    response_serializer=biometry__pb2.SystemStatusResponse.SerializeToString,
            ),
            'ControlService': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlService,
                    request_deserializer=biometry__pb2.ControlServiceRequest.FromString,
                    response_serializer=biometry__pb2.StatusResponse.SerializeToString,
            ),
            'ControlDoor': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlDoor,
                    request_deserializer=biometry__pb2.ControlDoorRequest.FromString,
                    response_serializer=biometry__pb2.StatusResponse.SerializeToString,
            ),
            'ScanHardware': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanHardware,
                    request_deserializer=biometry__pb2.Empty.FromString,
                    response_serializer=biometry__pb2.ScanHardwareResponse.SerializeToString,
            ),
            'GetLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=biometry__pb2.GetLogsRequest.FromString,
                    response_serializer=biometry__pb2.GetLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biometry.Gatekeeper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('biometry.Gatekeeper', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gatekeeper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/RegisterUser',
            biometry__pb2.RegisterUserRequest.SerializeToString,
            biometry__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBiometry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/AddBiometry',
            biometry__pb2.AddBiometryRequest.SerializeToString,
            biometry__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/RemoveUser',
            biometry__pb2.IdRequest.SerializeToString,
            biometry__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/ListUsers',
            biometry__pb2.ListUsersRequest.SerializeToString,
            biometry__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddZone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/AddZone',
            biometry__pb2.AddZoneRequest.SerializeToString,
            biometry__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListZones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/ListZones',
            biometry__pb2.ListZonesRequest.SerializeToString,
            biometry__pb2.ListZonesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/AddRoom',
            biometry__pb2.AddRoomRequest.SerializeToString,
            biometry__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/ListRooms',
            biometry__pb2.ListRoomsRequest.SerializeToString,
            biometry__pb2.ListRoomsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/AddDevice',
            biometry__pb2.AddDeviceRequest.SerializeToString,
            biometry__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/ListDevices',
            biometry__pb2.ListDevicesRequest.SerializeToString,
            biometry__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/RemoveDevice',
            biometry__pb2.IdRequest.SerializeToString,
            biometry__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/GrantAccess',
            biometry__pb2.GrantAccessRequest.SerializeToString,
            biometry__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAccessRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/SetAccessRules',
            biometry__pb2.SetAccessRulesRequest.SerializeToString,
            biometry__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/GetUserAccess',
            biometry__pb2.IdRequest.SerializeToString,
            biometry__pb2.GetUserAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/CheckAccess',
            biometry__pb2.CheckAccessRequest.SerializeToString,
            biometry__pb2.AccessCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/GetSystemStatus',
            biometry__pb2.Empty.SerializeToString,
            biometry__pb2.SystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/ControlService',
            biometry__pb2.ControlServiceRequest.SerializeToString,
            biometry__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlDoor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/ControlDoor',
            biometry__pb2.ControlDoorRequest.SerializeToString,
            biometry__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanHardware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/ScanHardware',
            biometry__pb2.Empty.SerializeToString,
            biometry__pb2.ScanHardwareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Gatekeeper/GetLogs',
            biometry__pb2.GetLogsRequest.SerializeToString,
            biometry__pb2.GetLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VisionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFace = channel.unary_unary(
                '/biometry.Vision/ProcessFace',
                request_serializer=biometry__pb2.ImageFrame.SerializeToString,
                response_deserializer=biometry__pb2.BioResult.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/biometry.Vision/GetStatus',
                request_serializer=biometry__pb2.Empty.SerializeToString,
                response_deserializer=biometry__pb2.ServiceStatus.FromString,
                _registered_method=True)


class VisionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFace': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFace,
                    request_deserializer=biometry__pb2.ImageFrame.FromString,
                    response_serializer=biometry__pb2.BioResult.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=biometry__pb2.Empty.FromString,
                    response_serializer=biometry__pb2.ServiceStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biometry.Vision', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('biometry.Vision', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Vision(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Vision/ProcessFace',
            biometry__pb2.ImageFrame.SerializeToString,
            biometry__pb2.BioResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Vision/GetStatus',
            biometry__pb2.Empty.SerializeToString,
            biometry__pb2.ServiceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AudioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVoice = channel.unary_unary(
                '/biometry.Audio/ProcessVoice',
                request_serializer=biometry__pb2.AudioChunk.SerializeToString,
                response_deserializer=biometry__pb2.BioResult.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/biometry.Audio/GetStatus',
                request_serializer=biometry__pb2.Empty.SerializeToString,
                response_deserializer=biometry__pb2.ServiceStatus.FromString,
                _registered_method=True)


class AudioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessVoice,
                    request_deserializer=biometry__pb2.AudioChunk.FromString,
                    response_serializer=biometry__pb2.BioResult.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=biometry__pb2.Empty.FromString,
                    response_serializer=biometry__pb2.ServiceStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biometry.Audio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('biometry.Audio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Audio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Audio/ProcessVoice',
            biometry__pb2.AudioChunk.SerializeToString,
            biometry__pb2.BioResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biometry.Audio/GetStatus',
            biometry__pb2.Empty.SerializeToString,
            biometry__pb2.ServiceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
